package com.codetreatise.controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.ToggleGroup;

import java.net.URL;
import java.util.ResourceBundle;

import org.springframework.stereotype.Controller;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.ToggleButton;

import javafx.scene.control.Spinner;

import javafx.scene.chart.BarChart;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

@Controller
public class SubjetController implements Initializable {
	@FXML
	private ListView<?> listClasse;
	@FXML
	private ListView<?> listNiveau;
	@FXML
	private ListView<?> ListMatiere;
	@FXML
	private TableView<?> noteTab;
	@FXML
	private TableColumn<?, ?> id_tab;
	@FXML
	private TableColumn<?, ?> id_studentTab;
	@FXML
	private TableColumn<?, ?> nom;
	@FXML
	private TableColumn<?, ?> prenom;
	@FXML
	private TableColumn<?, ?> normalTab;
	@FXML
	private TableColumn<?, ?> ccTab;
	@FXML
	private TableColumn<?, ?> finalNoteTab;
	@FXML
	private TableColumn<?, ?> moyenneTab;
	@FXML
	private TableColumn<?, ?> rang;
	@FXML
	private TableColumn<?, ?> observation;
	@FXML
	private Button add;
	@FXML
	private Button edit;
	@FXML
	private TextField recherche;
	@FXML
	private TextField id;
	@FXML
	private TextField normal;
	@FXML
	private TextField cc;
	@FXML
	private TextField finalNote;
	@FXML
	private Spinner<?> id_student;
	@FXML
	private TextField matiere;
	@FXML
	private BarChart<?, ?> Barchart;
	@FXML
	private ListView<?> listStudent;
	@FXML
	private ToggleButton nul;
	@FXML
	private ToggleGroup toggle1;
	@FXML
	private ToggleButton faible;
	@FXML
	private ToggleGroup toggle;
	@FXML
	private ToggleButton mediocre;
	@FXML
	private ToggleButton passable;
	@FXML
	private ToggleButton bien;
	@FXML
	private ToggleButton tresBien;
	@FXML
	private ToggleButton exellent;
	@FXML
	private Button validate;

	// Event Listener on Button.onAction
	@FXML
	public void handleRefreshClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#add].onAction
	@FXML
	public void handleAddClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#edit].onAction
	@FXML
	public void handleEditClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#validate].onAction
	@FXML
	public void handleValidateClick(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
	}
}
