package com.codetreatise.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import org.springframework.stereotype.Controller;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.MenuItem;

import javafx.scene.control.ComboBox;

import javafx.scene.control.PasswordField;

import javafx.scene.input.KeyEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

@Controller
public class UserController {
	@FXML
	private Label userId;
	@FXML
	private ComboBox user;
	@FXML
	private ComboBox access;
	@FXML
	private TextField login;
	@FXML
	private PasswordField password;
	@FXML
	private Button handleEditClick;
	@FXML
	private Button reset;
	@FXML
	private TableView userTable;
	@FXML
	private TableColumn idC;
	@FXML
	private TableColumn FirstNameC;
	@FXML
	private TableColumn LastNameC;
	@FXML
	private TableColumn accessC;
	@FXML
	private TableColumn LoginC;
	@FXML
	private TableColumn passC;
	@FXML
	private TableColumn editC;
	@FXML
	private MenuItem deleteUsers;
	@FXML
	private ComboBox filtre;

	// Event Listener on MenuItem.onAction
	@FXML
	public void exit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#reset].onAction
	@FXML
	public void handleResetClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void handleSaveClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#deleteUsers].onAction
	@FXML
	public void deleteUsers(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void handleRefreshClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField.onKeyReleased
	@FXML
	public void handleFilterPressed(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void handlePrintClick(ActionEvent event) {
		// TODO Autogenerated
	}
}
